name: 'Pull Detached Remote'
description: 'Creates a detached upstream branch (from another repo) and a corresponding PR and updates it automatically'
author: 'litetex'
inputs:
  identitymail:
    description: 'Email for commits to the upstream branch'
    required: false
    default: 'action@github.com'
  identityuser:
    description: 'Username for commits to the upstream branch'
    required: false
  prassignees:
    description: 'Assignees (usernames) for the created pull request (separated by ",")'
    required: false
  prreviewers:
    description: 'Reviewers (usernames) for the created pull request (separated by ",")'
    required: false
  prlabels:
    description: 'Labels for the created pull request (separated by ",")'
    required: false
  workingrepopath:
    description: 'Path to working repo'
    required: false
    default: '/github/workspace'
  originbranch:
    description: 'The branch(name) to merge the PR into; default is Github-Repos default-Branch'
    required: false
  upstreamrepo:
    description: 'Detached remote repository that should be used'
    required: true
  upstreambranch:
    description: 'Detached remote branch that should be used; WARNING: It is recommend to set this branch, otherwise the process may be inperformant'
    required: false
  updatebranch:
    description: 'Name of the branch that will be created in the origin-Repo with the changes from upstream-Repo/upstream-Branch; default is a auto generated name from the upstreamRepo + Branch'
    required: false
  ignoreprotocol: 
    description: 'Ignores the protocol (http/https) when generating the updatebranch name; possible values=1 or true'
    required: false
  upstreamcredmode:
    description: 'Determines which credentials are used for authetification at upstreamrepo (or how they are determined / used); Valid inputs are AUTO (default/if not set), NONE, GITHUB or CUSTOM'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--identitymail'
  - '${{ inputs.identitymail }}'
  - '--identityuser'
  - '${{ inputs.identityuser }}'
  - '--prassignees'
  - '${{ inputs.prassignees }}'
  - '--prreviewers'
  - '${{ inputs.prreviewers }}'
  - '--prlabels'
  - '${{ inputs.prlabels }}'
  - '--workingrepopath'
  - '${{ inputs.workingrepopath }}'
  - '--originbranch'
  - '${{ inputs.originbranch }}'
  - '--upstreamrepo'
  - '${{ inputs.upstreamrepo }}'
  - '--upstreambranch'
  - '${{ inputs.upstreambranch }}'
  - '--updatebranch'
  - '${{ inputs.updatebranch }}'
  - '--ignoreprotocol'
  - '${{ inputs.ignoreprotocol }}'
  - '--upstreamcredmode'
  - '${{ inputs.upstreamcredmode }}'
branding:
  icon: 'zap'  
  color: 'yellow'
