name: 'Pull Detached Remote'
description: 'Creates an detached upstream branch and a corresponding PR from another repo and updates it automatically'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-down-circle'  
  color: 'yellow'
