name: Develop Tagger

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Remove existing tag
      run: |
        git tag -d dev
        git push origin :refs/tags/dev
        git tag dev
        git push origin --tags
        
    - name: Set tag again
      run: |
        git tag dev
        git push origin --tags
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: vdev
        release_name: vdev
        commitish: develop
        body: |
          ### Latest develop release
          Ref: ${{ github.ref }}
        draft: false
        prerelease: true
